### PR TITLE
Slovak translation

### PR DESCRIPTION
**Pull request by dodog**
Very nice extension. I have added Slovak translation.

### CODE REVIEW

**Comment by pratap-panabaka** [comment]
Hi @dodog I will review this in a week and then merge it.
Solvak means is it a russian language?

Thank You.

**Comment by dodog** [comment]
Hi @PRATAP-KUMAR, thanks. 
No, Slovak is not Russian. Both belong to Slavic languages, but they are different.

**Comment by pratap-panabaka** [comment]
Hi

After my first message I googled and found that it's a country from Europe (.sk) I googled your web address.

Will get back to you after I review the code with your translation files. Probably in a week.

See you then.

**Comment by pratap-panabaka** [comment]
Hi @dodog
I have tested the translations after installing Slovak language in my system. Working great.

image

I would like to connect with you, can you please drop a test mail pratap@fastmail.com please.

Thanks.

**Pull request merged**
